"""incorrect naming for foreign key

Revision ID: 8d1966afcdb2
Revises: 964721fe74e8
Create Date: 2020-02-22 22:14:48.123729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d1966afcdb2'
down_revision = '964721fe74e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('tournament_id', sa.Integer(), nullable=True))
    op.drop_constraint('game_tournament_fkey', 'game', type_='foreignkey')
    op.create_foreign_key(None, 'game', 'tournament', ['tournament_id'], ['id'])
    op.drop_column('game', 'tournament')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('tournament', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.create_foreign_key('game_tournament_fkey', 'game', 'tournament', ['tournament'], ['id'])
    op.drop_column('game', 'tournament_id')
    # ### end Alembic commands ###
